version: '3'
services:
  doko-graphql:
    env_file:
      - ./dev.env
      - ./mysql-dev.env
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes: 
      - './certs:/etc/ssl/certs'
    networks:
      - network-doko

  mysql:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./mysql-dev.env
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=password --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 30s
      retries: 10
    depends_on:
      - "adminer"
    networks:
      - network-doko

  adminer:
    image: adminer
    ports:
      - 8001:8080
    networks:
      - network-doko

networks:
  network-doko: