// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Note struct {
	Name  string  `json:"name"`
	Steps []*Step `json:"steps"`
}

type Step struct {
	Title string  `json:"title"`
	Txt   string  `json:"txt"`
	URL   *string `json:"url"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
